library;

export 'src/app_module.dart';

export 'package:path_provider/path_provider.dart';
export 'package:flutter_modular/flutter_modular.dart';
export 'package:intl/intl.dart';
export 'package:intl/date_symbol_data_local.dart';
export 'package:hive_flutter/hive_flutter.dart';
export 'package:email_validator/email_validator.dart';
export 'package:flutter_bloc/flutter_bloc.dart';
export 'package:supabase_flutter/supabase_flutter.dart';
export 'package:google_maps_flutter/google_maps_flutter.dart';
export 'package:flutter_svg/flutter_svg.dart';
export 'package:dartz/dartz.dart' hide State;
export 'package:diacritic/diacritic.dart';
export 'package:cached_network_image/cached_network_image.dart';
export 'package:bloc_concurrency/bloc_concurrency.dart';
export 'src/auth/infra/exceptions/supa_auth_exception.dart';
export 'src/core/infra/exceptions/generic_exception.dart';
export 'src/core/configs/app_configs.dart';
export 'src/core/configs/app_routes.dart';
export 'src/core/configs/api_keys.dart';
export 'src/core/configs/no_glow_behavior.dart';
export 'src/core/configs/generic_bloc_observer.dart';

export 'src/design_system/themes.dart';
export 'src/design_system/configs/app_images.dart';
export 'src/design_system/configs/app_fonts.dart';
export 'src/design_system/configs/app_icons.dart';
export 'src/design_system/configs/app_colors.dart';

export 'src/design_system/components/search/search_widget.dart';
export 'src/design_system/components/custom_behaviors/custom_reload_scroll_widget.dart';
export 'src/design_system/components/loading/loading_widget.dart';
export 'src/design_system/components/loading/cupertino_sliver_widget.dart';
export 'src/design_system/components/loading/refresh_indicator_widget.dart';
export 'src/design_system/components/guideline/guideline_widget.dart';
export 'src/design_system/components/slide_cards/slide_cards_widget.dart';
export 'src/design_system/components/shimmer/shimmer_widget.dart';
export 'src/design_system/components/buttons/icon_button_widget.dart';
export 'src/design_system/components/buttons/icon_widget.dart';
export 'src/design_system/components/buttons/floating_button_widget.dart';
export 'src/design_system/components/buttons/back_button_widget.dart';
export 'src/design_system/components/buttons/loading_button_widget.dart';
export 'src/design_system/components/buttons/switch_button_widget.dart';
export 'src/design_system/components/buttons/button_widget.dart';
export 'src/design_system/components/forms/form_field_widget.dart';
export 'src/design_system/components/chips/choice_chips_widget.dart';
export 'src/design_system/components/chips/own_choice_chips_widget.dart';
export 'src/design_system/components/forms/template_form_widget.dart';
export 'src/design_system/components/forms/formatters/phone_input_formatter.dart';
export 'src/design_system/components/forms/formatters/cep_input_formatter.dart';
export 'src/design_system/components/forms/formatters/date_input_formatter.dart';
export 'src/design_system/components/covers/album_cover_widget.dart';
export 'src/design_system/components/lists/lyrics_list_widget.dart';
export 'src/design_system/components/lists/grid_balls_tile_widget.dart';
export 'src/design_system/components/lists/verses_list_widget.dart';
export 'src/design_system/components/lists/custom_reorderable_list_widget.dart';
export 'src/design_system/components/carousel/carousel_widget.dart';
export 'src/design_system/components/checkbox/custom_check_box.dart';
export 'src/design_system/components/dropdowns/dropdown_widget.dart';
export 'src/design_system/components/exceptions/generic_error_view.dart';
export 'src/design_system/components/exceptions/no_connection_view.dart';
export 'src/design_system/components/exceptions/unknown_route_view.dart';
export 'src/auth/components/auth_circle_avatar_widget.dart';

export 'src/auth/components/stores/auth_circle_avatar_store.dart';
export 'src/design_system/components/bottom_bar/material_bottom_bar_widget.dart';
export 'src/design_system/components/dialogs/options_dialog_widget.dart';
export 'src/design_system/components/dialogs/confirm_dialog_widget.dart';
export 'src/design_system/components/dialogs/add_lyrics_dialog_widget.dart';
export 'src/design_system/components/toasts/toasts_widget.dart';
export 'src/design_system/components/side_bar/side_bar_widget.dart';
export 'src/design_system/components/top_bar/back_auth_top_bar_widget.dart';
export 'src/design_system/components/top_bar/service_top_bar_widget.dart';
export 'src/design_system/components/top_bar/logo_icon_widget.dart';
export 'src/design_system/components/top_bar/title_top_bar_widget.dart';
export 'src/design_system/components/scroll_transform/scroll_transform_item.dart';
export 'src/design_system/components/scroll_transform/scroll_transform_view.dart';
export 'src/design_system/components/icons/hide_icon_widget.dart';

export 'src/lyrics/components/stores/manage_lyric_store.dart';
export 'src/events/components/stores/create_event_store.dart';
export 'src/services/components/stores/manage_service_store.dart';
export 'src/services/components/stores/service_store.dart';
export 'src/design_system/stores/search_lyrics_store.dart';
export 'src/lyrics/components/stores/lyrics_list_store.dart';
export 'src/design_system/stores/slide_cards_store.dart';
export 'src/design_system/stores/search_store.dart';

export 'src/core/domain/use_cases/use_cases.dart';
export 'src/lyrics/domain/entities/lyric_entity.dart';
export 'src/lyrics/domain/entities/verse_entity.dart';
export 'src/services/domain/entities/service_entity.dart';
export 'src/services/domain/entities/services_entity.dart';
export 'src/auth/domain/entities/user_entity.dart';
export 'src/auth/domain/entities/auth_credentials.dart';
export 'src/lyrics/domain/entities/liturgy_entity.dart';
export 'src/events/domain/entities/event_entity.dart';

export 'src/core/infra/repositories/repositories.dart';
export 'src/services/infra/adapters/services_adapter.dart';
export 'src/events/infra/adapters/event_adapter.dart';
export 'src/lyrics/infra/adapters/liturgy_adapter.dart';
export 'src/lyrics/infra/adapters/verse_adapter.dart';
export 'src/lyrics/infra/adapters/lyric_adapter.dart';
export 'src/lyrics/infra/dtos/search_lyrics_dto.dart';
export 'src/services/infra/adapters/service_adapter.dart';
export 'src/auth/infra/hive_dtos/hive_credentials_dto.dart';
export 'src/auth/infra/hive_dtos/hive_user_dto.dart';
export 'src/core/infra/use_cases/use_cases.dart';

export 'src/core/external/repositories/supa_repository.dart';
export 'src/core/external/repositories/hive_repository.dart';

export 'src/shared/mixins/launch_url_mixin.dart';
export 'src/shared/mixins/date_mixin.dart';
export 'src/shared/mixins/clipboard_mixin.dart';
export 'src/shared/mixins/format_mixin.dart';
export 'src/shared/mixins/validation_mixin.dart';
export 'src/shared/mixins/connectivity_mixin.dart';
export 'src/shared/mixins/device_info_mixin.dart';
export 'src/shared/mixins/image_mixin.dart';
export 'src/core/overall_states/generics.dart';
export 'src/core/overall_states/generic_event_bus.dart';
export 'src/shared/utils/supa_services_util.dart';
export 'src/shared/utils/responsivity_util.dart';
export 'src/shared/utils/analytics_util.dart';
export 'src/shared/utils/mock_util.dart';
export 'src/shared/utils/app_links_util.dart';


export 'src/auth/domain/use_cases/auth_use_cases.dart';
export 'src/auth/external/repositories/supa_auth_repository.dart';