package io.flutter.plugins;

import io.flutter.embedding.engine.FlutterEngine;

/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
public final class GeneratedPluginRegistrant {

  public static void registerWith(FlutterEngine flutterEngine) {
  }
}
